name: states_rebuilder_groqhealth
description: Modified version of states_rebuilder 4.0.0+1 for Groq Health.
version: 4.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
